name: BE CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 소스 코드 체크아웃 후 backend 디렉토리로 이동
      - uses: actions/checkout@v4

      # backend 디렉토리를 루트 디렉토리로 설정
      - name: Change directory to backend
        run: cd backend
        working-directory: backend

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
        working-directory: backend
      
      # Gradle 실행 권한 설정
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
        working-directory: backend

      # Gradle 빌드 실행
      - name: Build with Gradle Wrapper
        run: ./gradlew build
        working-directory: backend



