name: BE CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    permissions:
      contents: read
    steps:
      # 소스 코드 체크아웃 후 backend 디렉토리로 이동
      - uses: actions/checkout@v4

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 실행 권한 설정
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      # Gradle 빌드 실행
      - name: Build with Gradle Wrapper
        run: ./gradlew build



